# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: message.proto for package 'sphinyx'
# Original file comments:
# We're using proto3 syntax

require 'grpc'
require 'message_pb'

module Sphinyx
  module ChatService
    # This is the service for our API
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'sphinyx.ChatService'

      rpc :Connect, ChatRequest, ChatResponse
      rpc :SendMessage, ChatRequest, ChatResponse
    end

    Stub = Service.rpc_stub_class
  end
end
