# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "sphinyx.ChatRequest" do
    optional :id, :string, 1
    optional :client, :string, 2
    optional :message, :string, 3
  end
  add_message "sphinyx.ChatResponse" do
    optional :id, :string, 1
    optional :message, :string, 2
  end
end

module Sphinyx
  ChatRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("sphinyx.ChatRequest").msgclass
  ChatResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("sphinyx.ChatResponse").msgclass
end
